### ISSUE TITLE
"unsafe" imported and not used

### ISSUE THREAD

**Issue by tsingbx** [goplus/llcppg#105]
llcppgtest sqlite3

<img width="510" alt="image" src="https://github.com/user-attachments/assets/14422547-01ce-4ce7-90f9-96522c6d8307" />

**Comment by luoliwoshang** [comment]
[#](https://github.com/goplus/llcppg/pull/111) 在这个测试用例中，unsafe 正常被引用

**Comment by luoliwoshang** [comment]
https://github.com/goplus/llcppg/pull/111 测试用例中复现了这个问题
