### ISSUE TITLE
llcppg: intmax_t... type not exist;nil underlying type panic

### ISSUE THREAD

**Issue by tsingbx** [goplus/llcppg#46]
```c
#  include <stdint.h>
typedef intmax_t ossl_intmax_t;
typedef uintmax_t ossl_uintmax_t;
# endif
```

**Comment by tsingbx** [comment]
2024/12/13 18:09:59 NewTypedefDecl ossl_intmax_t Fail: intmax_t not found sys type intmax_t in _types/_intmax_t.h not found in package github.com/goplus/llgo/c, full path /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/_types/_intmax_t.h
2024/12/13 18:09:59 NewTypedefDecl ossl_uintmax_t Fail: uintmax_t not found sys type uintmax_t in _types/_uintmax_t.h not found in package github.com/goplus/llgo/c, full path /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/_types/_uintmax_t.h
panic: underlying type must not be nil

**Comment by luoliwoshang** [comment]
这是个来自于系统头文件的类型，该头文件类型会自动转发引用 llgo/c 下的类型，对此我们需要在llgo/c 中添加类型映射即可

**Comment by tsingbx** [comment]
https://github.com/goplus/llgo/pull/918

**Comment by luoliwoshang** [comment]
该问题出现于typedef 的underlying type是一个不完整定义的情况下，因为在创建向前声明时，对应的类型还未初始化，所以导致创建新的类型时underlying type为nil
